module: frontend
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /opensearch.xml
  static_files: opensearch.xml
  upload: opensearch.xml

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /node_modules
  static_dir: node_modules

- url: /angularfire2
  static_dir: node_modules/angularfire2

