ahoyapi: v2
usage: Commands for running and updating stackbot
commands:
  up:
    usage: run stackbot locally.
    cmd: dev_appserver.py --skip_sdk_update_check=true backend & cd frontend && ng serve
  pip-install:
    usage: python pip, but locally vendored.
    cmd: pip install -t lib {{args}}
  console:
    usage: open the app engine web python console.
    cmd: open 'http://localhost:8000/console'
  deploy:
    usage: deploy the app to google app engine
    cmd: appcfg.py -A devinci-stackbot -V {{args}} update .
  deps:
    usage: Load and install all dependencies.
    cmd: |
      npm install -g angular-cli typings
      npm install
      typings install
  build:
    cmd: ng build
    usage: Build all of the files necessary to serve the site into the /dist folder.
