ahoyapi: v2
usage: Commands for running and updating stackbot
commands:
  up:
    usage: run stackbot locally.
    cmd: |
      cd default && ng build --watch=true &
      dev_appserver.py --skip_sdk_update_check=true default backend
  front-build:
    usage: build the frontend files.
    cmd: cd default && ng build --watch=true
  pip-install:
    usage: python pip, but locally vendored.
    cmd: cd backend && pip install -t lib {{args}}
  console:
    usage: open the app engine web python console.
    cmd: open 'http://localhost:8000/console'
  deploy:
    usage: deploy the app to google app engine
    cmd: appcfg.py -A devinci-stackbot -V {{args}} update default backend
  deps-frontend:
    usage: Load and install all dependencies.
    cmd: |
      npm install -g angular-cli typings
      cd default
      npm install
      typings install
  deps-backend:
    usage: Load and install all backend dependencies.
    cmd: |
      cd backend &&
      ahoy pip-install -- -r requirements.txt
  build:
    cmd: cd default && ng build
    usage: Build all of the files necessary to serve the site into the /dist folder.
  test:
    cmd: |
      set -e
      cd default &&
      if [ $CIRCLE_TEST_REPORTS ]; then
        echo '> Adding junit output to $CIRCLE_TEST_REPORTS'
        export JUNIT_DIR=$CIRCLE_TEST_REPORTS
        FLAGS='--reporters=junit,progress'
      fi
      ng test --watch=false $FLAGS
      ng lint
    usage: Run the frontend unit tests.
