runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/q
  script: main.app

- url: /
  static_files: index.html
  upload: index.html

- url: /opensearch.xml
  static_files: opensearch.xml
  upload: opensearch.xml

- url: /script.js
  static_files: script.js
  upload: script.js

- url: /firebase.js
  static_files: firebase.js
  upload: firebase.js

- url: /style.css
  static_files: style.css
  upload: style.css

