module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /opensearch.xml
  static_files: opensearch.xml
  upload: opensearch.xml

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: (.*)/
  static_files: dist\1/index.html
  upload: dist

- url: /(.*\.(js|map))$
  static_files: dist/\1
  upload: dist

- url: /(.*)$
  static_files: icons/\1
  upload: icons


skip_files:
- node_modules
- src
- tmp
- typings
- e2e
