module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /opensearch.xml
  static_files: opensearch.xml
  upload: opensearch.xml

- url: (.*)/
  static_files: webpack-dist\1/index.html
  upload: webpack-dist

- url: (.*)
  static_files: webpack-dist\1
  upload: webpack-dist


skip_files:
- node_modules
- src
- tmp
- typings
- e2e
